name: "02 - Understanding Events"
on:
    workflow_dispatch:
    push:
      branches: "main"
      paths:
        - "02-Workflow-Triggers/**"
    pull_request:
      branches: "main"
      paths:
        - "02-Workflow-Triggers/**"
    schedule:
        - cron: "*/7 * * * *"

jobs:
    event-info-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Trigger Event
              run: echo "My trigger event is ${{ github.event_name }} event"
