# name: "02b-ci-events.yml"


# on:
#     workflow_dispatch:
#     push:
#       branches: "main"
#     pull_request:
#       branches: "main"

#     schedule:
#         - cron: "*/7 * * * *"




# jobs:
#     event-info-job:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Print Trigger Event
#               run: echo "My trigger event is ${{ github.event_name }} event"
